<?php
/**
 * Created by PhpStorm.
 * User: chenmingming
 * Date: 2017/1/10
 * Time: 21:22
 */

namespace mmxs\mmapi\tests;

use mmapi\core\Cache;
use mmapi\core\Config;
use mmapi\wechat\cache\CacheProvider;
use mmapi\wechat\log\EchologProvider;
use mmapi\wechat\Wechat;
use PHPUnit\Framework\TestCase;
use Symfony\Component\Validator\Mapping\CascadingStrategy;

class WechatTest extends TestCase
{
    public function setUp()
    {

        parent::setUp(); // TODO: Change the autogenerated stub

        Config::batchSet([
            'cache'  => [
                'type'    => 'complex',
                'default' => [
                    'type'          => "file",
                    'expire'        => 0,
                    'cache_subdir'  => false,
                    'prefix'        => '123',
                    'path'          => '.',
                    'data_compress' => false,
                ],
            ],
            'wechat' => [
                'config' => [
                    'appid'      => 'wxd2c4732b5f9cd99d',
                    'app_secret' => '3719c70d5a101b4255586ce6f45a98a3',
                    'app_token'  => 'yuqi_weixin',
                    'app_aeskey' => 'MqAuKoex6FyT5No0OcpRy22cThGs0P1vz4mJ2gwvvkF',
                    'debug'      => true,
                ],
            ],
        ]);
    }

    public function test1()
    {
        $rs = Cache::set('test1', '123');
        $this->assertEquals(Cache::get('test1'), '123');
        print_r(Config::get('wechat'));
        $wechat = new Wechat(Config::get('wechat'), new CacheProvider());
        $wechat->setLogger(new EchologProvider());

        echo $wechat->getAccessToken();

        $wechat->getInitiativeReponse()->text('22', 'hello');
    }
}